### ISSUE TITLE
Safe Mode

### ISSUE THREAD

**Issue by Pintu7** [ioscreatix/Intelix#1]
With new version Intellix 1.1.0 i go in SafeMode.
Electra B10 i6s 11.1.2.
I installed latest versione and it worked. Since i installed 1.1.0 also previous version not working anymore.
Pm me if i can be useful with some logs or anything else can help you dev

**Comment by andrewwiik** [comment]
Yeah if you could post logs

**Comment by Pintu7** [comment]
This should be the correct log
[SpringBoard-2018-02-25-182040.zip](https://github.com/ioscreatix/Intelix/files/1756518/SpringBoard-2018-02-25-182040.zip)
