### ISSUE TITLE
Text in header is black

### ISSUE THREAD

**Issue by pmpunzalan** [ioscreatix/Intelix#106]
I think it is having a conflict with Noctis. The text in the header is black.

**Comment by sascha85** [comment]
Yes, would be nice if dev could fix this. 
A workaround for the moment was using colorbanners 2

**Comment by Atlanta** [comment]
Same for me.

**Device Model :**
iPhone10,6 (iPhone X 64 GB)

**iOS Version:**
11.3.1

**Comment by pmpunzalan** [comment]
Confirmed fixed in latest update.
