### ISSUE TITLE
Springboard crash I believe may have been associated w/ latest build

### ISSUE THREAD

**Issue by willrj93** [ioscreatix/Intelix#11]
Received a notification on the lock screen while the screen was awake, it crashed SpringBoard and through me into Electra's "safe mode"

I think this is the crash log but I apologize if I got it wrong; I've never submitted a crash log I didn't obtain via CrashReporter before.

[SpringBoard-2018-02-26-203709.txt](https://github.com/ioscreatix/Intelix/files/1760914/SpringBoard-2018-02-26-203709.txt)

**Comment by andrewwiik** [comment]
Make sure you use 1.1.2

**Comment by Revulate** [comment]
I believe I'm getting the same issue. iPhone X 11.1.2 Electra 1.0.2


[SpringBoard-2018-02-28-201312.txt](https://github.com/ioscreatix/Intelix/files/1769667/SpringBoard-2018-02-28-201312.txt)
