### ISSUE TITLE
Notifications not collapsing into "Show n more"

### ISSUE THREAD

**Issue by mattrberry** [ioscreatix/Intelix#14]
Looking at the picture in [this tweet](https://twitter.com/Andywiik/status/968245890623377408), it seems like the notifications are supposed to hide themselves into the "Show n more" button. This is not happening for me. Is this planned for a future release, or should this be working?

iPhone 8
iOS 11.0.3
Electra 1.0.2
Intelix 1.1.2

**Comment by andrewwiik** [comment]
It only currently works on the 'History' Section, it still has to be added to the new section
