### ISSUE TITLE
Notifications not always showing a transparent window 

### ISSUE THREAD

**Issue by dallasgroot** [ioscreatix/Intelix#21]
Sometimes (and I’ve had this happen to me in the past as well) with translucent windows showing on most notifications (only had a few to show here). 

![a4e7bdc3-dc6a-437c-a3a3-b1b2cb0dab55](https://user-images.githubusercontent.com/7484579/37134025-4b9037e0-224b-11e8-8ef5-e979344262fb.png)

iPhone 8(10,4)
iOS 11.1.2
InteliX 1.1.4
Electra 1.0.2

**Comment by andrewwiik** [comment]
This is a problem with Noctis, LQ will submitting a update  to fix this issue

**Comment by dallasgroot** [comment]
Ahh okay, sorry, I had issues with this before without noctis, you are right, that is the problem. Keep up the good work
