### ISSUE TITLE
InteliX not working for me

### ISSUE THREAD

**Issue by wood1030** [ioscreatix/Intelix#23]
Hi guys, 
InteliX sends me right to safe mode after install and restring every time. iX 11.1.2 Electra.

here is the list of tweaks installed:

![img_0053](https://user-images.githubusercontent.com/37167346/37135273-6586390a-2251-11e8-819a-4d4f680bd4b5.png)
![img_0054](https://user-images.githubusercontent.com/37167346/37135283-6de83b52-2251-11e8-9233-f00fb6fb681e.png)

Thanks.

**Comment by andrewwiik** [comment]
Settings is not a good list, please use cydia

**Comment by andrewwiik** [comment]
Also try uninstallting tweaks one by one, that is way too big of a list for me to replicate on my device

**Comment by wood1030** [comment]
ok

**Comment by wood1030** [comment]
uff

**Comment by andrewwiik** [comment]
Start off with ones that modify the lockscreen or notifications

**Comment by wood1030** [comment]
I'll go through them one by one and give you an update by tomorrow...it might take me a while :)

Thanks.

**Comment by andrewwiik** [comment]
Do you have LittleX installed by chance? I can tell you it isn't Palette btw

**Comment by wood1030** [comment]
I do not.

**Comment by andrewwiik** [comment]
Could you get me a tweak list from Cydia, Setting only shows tweaks that have settings

**Comment by wood1030** [comment]
Not sure how to do that other than send you screen shots of all the tweaks in cydia...suggestions?

**Comment by andrewwiik** [comment]
Just send screenshots

**Comment by wood1030** [comment]
ok

**Comment by wood1030** [comment]
give me a minute

**Comment by andrewwiik** [comment]
It isn't NoMoreSmallApps either

**Comment by wood1030** [comment]
ok

**Comment by wood1030** [comment]
incoming...

**Comment by wood1030** [comment]
![img_0055](https://user-images.githubusercontent.com/37167346/37135818-def77f4a-2253-11e8-8188-f86fa938375c.png)

**Comment by wood1030** [comment]
![img_0056](https://user-images.githubusercontent.com/37167346/37135838-ee42c8e2-2253-11e8-8118-f5c4fffe7485.png)

**Comment by wood1030** [comment]
![img_0057](https://user-images.githubusercontent.com/37167346/37135849-f8295844-2253-11e8-875c-43f5b5cf5be4.png)

**Comment by wood1030** [comment]
![img_0058](https://user-images.githubusercontent.com/37167346/37135857-01f83fa2-2254-11e8-9556-1c354d23b6d5.png)

**Comment by wood1030** [comment]
![img_0059](https://user-images.githubusercontent.com/37167346/37135862-0af95122-2254-11e8-8d59-e96c01f195de.png)

**Comment by wood1030** [comment]
![img_0060](https://user-images.githubusercontent.com/37167346/37135868-12fbcab2-2254-11e8-8770-011c4f310558.png)

**Comment by andrewwiik** [comment]
uninstall FastUnockX

**Comment by wood1030** [comment]
![img_0061](https://user-images.githubusercontent.com/37167346/37135879-242df580-2254-11e8-936e-0a54700be377.png)

**Comment by wood1030** [comment]
ok

**Comment by andrewwiik** [comment]
still need the rtest of the list though

**Comment by wood1030** [comment]
I have more screens

**Comment by wood1030** [comment]
![img_0062](https://user-images.githubusercontent.com/37167346/37135915-3fc97152-2254-11e8-8e7c-1731fa4204be.png)

**Comment by wood1030** [comment]
![img_0063](https://user-images.githubusercontent.com/37167346/37135937-50ab1b2e-2254-11e8-872d-7f9b4b759f8c.png)

**Comment by wood1030** [comment]
![img_0064](https://user-images.githubusercontent.com/37167346/37135962-66804604-2254-11e8-81fd-58c7d24834ee.png)

**Comment by wood1030** [comment]
![img_0065](https://user-images.githubusercontent.com/37167346/37135980-78446e38-2254-11e8-9d5f-d681c694ec2f.png)

**Comment by wood1030** [comment]
![img_0066](https://user-images.githubusercontent.com/37167346/37135990-7ef96da0-2254-11e8-8768-56c46f75a760.png)

**Comment by wood1030** [comment]
![img_0067](https://user-images.githubusercontent.com/37167346/37135997-85e73f0c-2254-11e8-8fdc-a21d04f71451.png)

this is the last one...uninstalling fastlockx now and will try intelix again...

**Comment by andrewwiik** [comment]
also remove picobanners2

**Comment by wood1030** [comment]
ok

**Comment by andrewwiik** [comment]
then tell me if it still sends you to safe mode

**Comment by wood1030** [comment]
will do

**Comment by wood1030** [comment]
Booya! Bingo! Bang! Seems all good in da hood :)

**Comment by wood1030** [comment]
Thanks sooo much...sorry for confusion with conflict post in wrong GitHub thread

**Comment by andrewwiik** [comment]
Noo I need to know which one

**Comment by andrewwiik** [comment]
Reinstall pIcoBanners and see if it still works

**Comment by wood1030** [comment]
Do you think it might be safe to try and install Fastunlockx or is that a known conflict?

**Comment by wood1030** [comment]
picobanners i can do without, really

**Comment by andrewwiik** [comment]
I need you to install it so I know whether the conflict was FastUnlock or PicoBanners

**Comment by wood1030** [comment]
well...i'll try one at a time and see which is the devil

**Comment by wood1030** [comment]
hmmmmm...that is bizarre....picobanners is installed now...no crash or safe mode but inteliXis acting differently. I now get the notifications scrolling from right to left in each notification. Is this normal?

**Comment by andrewwiik** [comment]
yes that is what PicoBanners does apparently

**Comment by andrewwiik** [comment]
well that debugging was useless I guess

**Comment by wood1030** [comment]
ah hah...interesting. I'll have to get used to it   lol

**Comment by wood1030** [comment]
thanks again for your help...i'll keep an eye on those two apps and hopefully we'll continue to be alright :)

**Comment by wood1030** [comment]
also i'll pay close attention to any new apps I might install for compatibility :)
