### ISSUE TITLE
Transparent Notifications

### ISSUE THREAD

**Issue by WillBishop** [ioscreatix/Intelix#36]
I know this was supposedly fixed but I'm still seeing it.

![See picture for detail](https://user-images.githubusercontent.com/17292672/37259617-6d639476-25d8-11e8-8d7e-9c730a5f1c61.PNG)

It doesn't show notification bodies though.

Tweak List:

Ah!Ah!Ah! 2.0 Beta 3
Alkaline
Anemone
appinst
AppList
AppSync Unified
Bioprotect X for iOS 11
Bloard
Cyllinder
DarkMessages (iOS 10)
DismissAnywhere
DockAlpha
Eclipse X Beta 10 (iOS 11) (**Disabled**)
FingerTouch
Flame
Flex 3 Beta
GuestMode2
Intelix
Milkshake
NoTrackpadDelay
Palette (**Disabled**)
RomanPasscode
Silo
Sonus
SwipeForMore
SwipeSelection Pro
TapTapFlip
tweakCompatible

**Comment by mina0887** [comment]
Same issue here still.

**Comment by RIPv1** [comment]
Also experiencing the same behavior on iPhone X (11.1.2) with the latest version of Intelix (1.1.4)

**Comment by WillBishop** [comment]
Still not fixed unfortunately
