### ISSUE TITLE
Crashing on newest version (1.1.6)

### ISSUE THREAD

**Issue by tomlube** [ioscreatix/Intelix#56]
https://pastebin.com/0ABxizit

**Comment by simsdj** [comment]
Same here

**Comment by Treqzi** [comment]
Sadly the random crashing keeps happening. Mostly happens while in landscape mode from what ive seen

**Comment by LaughingQuoll** [comment]
Due to a lack of CrashReporter, crash bugs will currently be ignored. The moment crash reporter is updated please reopen this issue with included crash reports.

Thank you!

**Comment by WillBishop** [comment]
What? That's ridiculous! People can attach crash logs. Andy cannot ignore the biggest problem with this tweak

**Comment by andrewwiik** [comment]
When the crash logs are useless yes i can and will, without a syslog or them being symbolicated they are basically garbage.
