### ISSUE TITLE
Incompatible With Colorbanners2

### ISSUE THREAD

**Issue by cvevea3** [ioscreatix/Intelix#57]
I have just bought intelix and am sadly going to have to uninstall it due to it not being compatible with my favorite tweak “colorbanners2”, I’m very disheartened because your tweak is just so great, but i want it to work with another great tweak. I hope you make a quick update for it so it works with colorbanners. Thanks and have a good day. (If you can’t, please let me know why on my twitter @watchawatchwhen so i can get some closure)

**Comment by LaughingQuoll** [comment]
Screenshots please
