### ISSUE TITLE
Springboard crashes when i open the coversheet/notifications centre

### ISSUE THREAD

**Issue by hotDoggey** [ioscreatix/Intelix#58]
As the title said my springboard keeps crashing. It has done it 3 times today, I uninstalled palette but it doesn’t seem like it has helped. Please fix, i payed for this and i cant even use it. Also sometimes there are two section for the same app.

**Comment by LaughingQuoll** [comment]
Due to a lack of CrashReporter, crash bugs will currently be ignored. The moment crash reporter is updated please reopen this issue with included crash reports.

Thank you!
