### ISSUE TITLE
Incompatible with PicoBanners2

### ISSUE THREAD

**Issue by JaydenJinx** [ioscreatix/Intelix#60]
Aww man seriously? I cannot function without PicoBanners or something similar. They need to be compatible before I actually use the tweak I paid for.

**Comment by LaughingQuoll** [comment]
Screenshots please.

**Comment by JaydenJinx** [comment]
https://imgur.com/a/PtETS

**Comment by LaughingQuoll** [comment]
Ok, that is a choice either Andrew or the dev picobanners 2 has made. For good reason.

**Comment by JaydenJinx** [comment]
Picobanners just modifies the initial banner, but intelix just modifies to notification center? right? why wouldnt they be compatible? (obviously im not a developer or know much about obj-c/iphones in general)

**Comment by andrewwiik** [comment]
You want the dead honest truth? PicoBanners2 was written like shit, I reversed some of its code, it is horrid.

**Comment by JaydenJinx** [comment]
I'll take your word for it, I trust you as a developer more than him purely based on work you've done. However, this has been my least buggy tweak I've installed. I've had zero issues (with the exception of a couple incompatibilities), so I will continue to use this instead of the others because the massive notification banners are one of the worst parts of iOS.
