### ISSUE TITLE
Now It Instantly Crashes for Me

### ISSUE THREAD

**Issue by SaigaYT** [ioscreatix/Intelix#64]
The new version will not let me out of safe mode until I uninstall. I only have one tweak that affects the lockscreen, Xen HTML, but the widgets don’t even affect the notifications, so I’m lost as to what the underlying problem could be. iOS 11.1, Electra 1.0.4, iPhone 7.

**Comment by SaigaYT** [comment]
Here is the tweak list:

Actual Battery: 2.0-4
Alkaline: 1.3
Alright Sans (iOS10/11): 1.1
Anemone: 2.1.7-3
App Admin: 1.0r-71
AppList: 1.5.14
Base Structure: 1-4
BigBoss Icon Set: 1.0
BioProtect X for iOS 11: 2.3-8
BlurryLaunch: 2.0
Bolders: 0.0.4-2
BoostedWifi: 1.0
Boxy 3 (iOS 11): 3.2.6-1+debug
ByeByeHUD: 1.1.3
CCMusicArtwork [Members Plus]: 0.0.5-1-5
Cephei: 1.12
CocoaTop: 2.0.2
CrashReporter: 1.15.1-1
CX.HS 4: 2.0
CX.HS 5: 2.0
CX.HS 7: 2.6
CX.HS 8: 1.0
CX.LS 10: 1.0
CX.LS 1: 2.0
CX.LS 2: 2.0
CX.LS 3: 2.0
CX.LS 4: 2.1
CX.LS 5: 2.0
CX.LS 6: 2.0
CX.LS 7: 2.0
CX.LS 8: 2.2
CX.LS 9: 2.3
Cydia Translations: 1.1.12
Destiny Zeppelin Logo Pack: 1.0.0
Destiny Zeppelin Logos: 1.0.1
DetailedPowerUsage: 1.0.2-1b
Dim: 1.5.2
DismissProgress: 1.0.3
DockXI For iOS8/9/10/11: 1.1.1
DoubleCut: 0.4.1-1
dubs iW buuf1: 1.0
dubs iW buuf2: 1.0.1
dubs iW buuf4: 1.0
dubs iW buuf5: 1.0
dubs iW dubsessenza146: 1.0
dubs iW essenza162: 1.0
dubs iW essenza163: 1.0
dubs iW essenza164: 1.0
dubs iW essenza170: 1.0
dubs iW essenza171: 1.0
dubs iW essenza172: 1.0
dubs iW essenza173: 1.0
dubs iW essenza174: 1.0
dubs iW essenza175: 1.0
dubs iW essenza70rev: 1.0
dubsIS2elixiriW2: 1.0
dubsIS2elixirSBHTML2GoogleBar: 1.0
Erica Utilities: 1:0.4.2
EVELYN's Repo Icons: 1.1
EW.WdgtPack.4: 1.0
Ext3nder Installer: 16.7
EzLocation: 0.0.5
EzRespring: 1.2-debug3
EzSafemode: 0.0.3
EzUICache: 0.0.3
Filza File Manager: 3.5.2-1
Flame: 1.3
FlatSafariURL: 0.0.1
Flipswitch: 1.0.15
FormulaOneOne: 1.0.1-3
Helvetica Neue Font for Anemone: 1.0
iCleaner Pro: 7.7.0
InfoStats 2 (No WebCycript): 1.0.2-1
iOS Firmware: 11.1
iPhone Firmware (/sbin): 0-1
libbulletin: 0.1-137
libcolorpicker: 1.6-1
libcrashreport: 1.1.0-1
Liberty: 0.2.2
libGitHubIssues: 0.0.1
libpackageinfo: 1.1.0.1-1
libSparkAppList: 0.0.4-1-2
libstatusbar: 1:0.9.9.0-1
libsymbolicate: 1.9.0-1
Link Identity Editor: 2:1.2.2-coolstar
Lockscreen Suite: 1.0.4-1
LowerInstall: 0.0~beta3
MakeCydiaBuyAgain: 1.0
MImport: 0.0~beta31a
MitsuhaXI: 0.2.0
MobileMiner: 1.0
MorePowerOptions: 1.3
MultiPatch: 3.0.0
NightOwl: 1.0.1
NoctisXI: 1.3.1
NoSharePlz: 1.0
NoSubstitute (Electra): 1.0-1
PalBreak: 1.1
Parallax: 0.7
pincrush: 0.9.2-2
PIPEnabler: 0.2
PreferenceLoader: 2.2.3-3
Profile Directory: 0-2
RocketBootstrap: 1.0.6
Rooster: 1.0.0
Safari Plus: 1.5
Silo: 1.0.0-4+debug
Spectre (formally Phantom): 0.1-4
Spotify New UI Enabler: 2.0
SugarCane: 1.0.0
SwipeForMore: 1.1.7
TapTime [Public]: 0.0.31
TechSupport Framework: 1.5.0.1-1
togglesafe: 1.0.2
TWSaveDm: 1.0
uasharedtools: 2.2r-31
UAUnbox: 0.0.2-1
VideoHUD: 2.2
Xen HTML: 0.4rc2
Zeppelin: 2.1.0-12

**Comment by iSalvox** [comment]
I removed all my tweak and still crash too. I don’t think it’s a problem of compatibility

**Comment by andrewwiik** [comment]
I don't offer support anymore, Intelix is personal project this point for my device, if it works on mine that is all I am worried about. Just downgrade the tweak in cydia to an older version that worked for you.

**Comment by iSalvox** [comment]
Yeah, now it works . You’re rock!

Last question: Will you add palette support ?

**Comment by andrewwiik** [comment]
No, Pallete was written horribly in terms of making it compatible, I suggest going with ColorBanners2

**Comment by iSalvox** [comment]
Ah ok, I’m using ColorBanners 2, but the text is only white and I can’t read it well. I’ve used Palette because it has text white or black.

I will try to contact the dev and I will ask him if he can add the black text on notifications
