### ISSUE TITLE
Intelix 1.2.3

### ISSUE THREAD

**Issue by rubenizag** [ioscreatix/Intelix#67]
Working Well For Me With ColorBanner Update. Possible To Add Support For AutoUnlock From SparkDev?
Keep Up The Good Work👌

**Comment by rubenizag** [comment]
1.1.8 Is Working With AutoUnlock, While 1.2.3 Isn’t Nor Was 1.2.0.

**Comment by rubenizag** [comment]
https://drive.google.com/open?id=1OkiHb9PlwDRC_MQgVwfrxcdIeYKrTrsp
Maybe Some Helpful Crash Reports?

**Comment by andrewwiik** [comment]
Uselss, need syslogs
