### ISSUE TITLE
Clear All - Doesn't work properly

### ISSUE THREAD

**Issue by ghost** [ioscreatix/Intelix#81]
Clear All - when I press this button, the notifications clear themselves, but when I respring my device they reappear again.
Clear - works just fine.

![iu](https://user-images.githubusercontent.com/15982085/39018617-3d3e9686-442f-11e8-8145-08a553c573f9.jpg)

Device: iPhone X
iOS: 11.1.2
Jailbreak tool: Electra 1.0.4
Tweak [list](https://pastebin.com/REbVVCxr)

**Comment by hitesh1khandelwal** [comment]
Same on iPhone 6s
