### ISSUE TITLE
Not in settings 

### ISSUE THREAD

**Issue by jpbeauch65** [ioscreatix/Intelix#99]
Electra 11.3.1 jailbreak. iPhone 8+. Intellix does install and works by doesn’t appear in settings. Thx. Just bought it using make cydiabuyagain

**Comment by narutojawad** [comment]
I have the same issue

**Comment by marco1006** [comment]
Same issue

**Comment by eddyg22** [comment]
Same issue as well. Really want to use this tweak!

**Comment by DrFA** [comment]
There is no “settings” for this tweak! Just Install&Play....no settings to configure

**Comment by eddyg22** [comment]
Where at? I dont see anywhere the app is?

**Comment by marco1006** [comment]
So, where iS! the group notification? Notifications are like always in iOS
11

**Comment by sascha85** [comment]
here also...tweak is working for me... iPhone X Electra 1131.... but there are not option in settings app.
i dont know if there are no or if its a bug

**Comment by JeffResc** [comment]
I don’t believe Intelix has any configuration options available. Once you install it, it just works and that’s it.
